# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: exPOTUS.com
email: contact@expotus.com
description: > # this means to ignore newlines until "baseurl:"
  Fun facts about ex-Presidents of the United States.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://expotus.com" # the base hostname & protocol for your site
twitter_username: haroldcheney
github_username:  haroldcheney
images_base: http://images.expotus.com.s3-website-us-west-2.amazonaws.com

# Build settings
markdown: kramdown

collections:
  expotuses:
    output: true
    permalink: /expotus/:path/
